### ISSUE TITLE
Generate and implement an SSL certificate

### ISSUE THREAD

**Issue by 035WasTaken** [JavaRockMC/javarock-site#12]

**Comment by dudebehinddude** [comment]
im going to buy the domain off of squarespace which includes an ssl certificate

**Comment by 035WasTaken** [comment]
by implement i mean ACTUALLY implement it not have plans to buy one

**Comment by dudebehinddude** [comment]
I'm saying it comes with the domain, you don't have to implement it, it's associated with the domain
