### ISSUE TITLE
Add a way to contact us besides Discord

### ISSUE THREAD

**Issue by 035WasTaken** [JavaRockMC/javarock-site#14]
Ideally, we could have the user sign in with discord and send us a message through the website which is then sent in a private channel in the Discord. Just seems like a fun idea I think.

**Comment by dudebehinddude** [comment]
probably a better idea than just telling the person to dm us because my dms are only open to people I'm friends w/in a server with

**Comment by dudebehinddude** [comment]
wait wouldnt it be a better idea to have a link to a google form? yeah sure you wouldnt really be able to have it sent to a channel but are we really gonna use that?

**Comment by dudebehinddude** [comment]
this would also make it easier to ask questions like how did you find the server and why they wanna join

**Comment by dudebehinddude** [comment]
oh yeah this is done already
